package com.tbp.visao;

import com.tbp.exception.CotacaoInvalidaException;
import com.tbp.exception.ProdutoInvalidoException;
import com.tbp.validation.ProdutoValidation;
import com.tbp.repository.*;
import com.tbp.model.*;
import com.tbp.validation.CotacaoValidacao;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.stereotype.Component;

@Component
public class Janela extends javax.swing.JFrame {

    @Autowired
    private ProdutoRepository produtoRepository;
    @Autowired
    private CotacaoRepository cotacaoRepository;
            
    private final boolean MODO_CADASTRO = true;
    private final boolean MODO_LISTAGEM = false;

    private final int TAB_PRODUTO = 0;
    private final int TAB_CATACO = 1;

    private ProdutoValidation produtoValidation;
    private CotacaoValidacao cotacaoValidation; 

    public Janela() throws ParseException {
        initComponents();

        this.produtoValidation = new ProdutoValidation();
        this.cotacaoValidation = new CotacaoValidacao();
        
        preencherTableProdutos(null);
        preencherTableCotacao(null);

        jtabPrincipal.setSelectedIndex(0);
        jtabProdutos.setSelectedIndex(0);
        jtabCotacao.setSelectedIndex(0);

        jcbSituacao.removeAllItems();
        jcbSituacao.addItem("Ativo");
        jcbSituacao.addItem("Inativo");
        
        MaskFormatter maskData = new MaskFormatter("##/##/####");    
        maskData.install(jtxtCotacaoValidade);
        
        NumberFormat amountFormat = NumberFormat.getCurrencyInstance();
        

        modificarEstado(MODO_LISTAGEM);
        
        carregarFornecedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtabPrincipal = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jtabProdutos = new javax.swing.JTabbedPane();
        jpnlProdutoListagem = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jtxtPesquisaProduto = new javax.swing.JTextField();
        jbtnExportacao = new javax.swing.JButton();
        jbtnPesquisarProduto = new javax.swing.JButton();
        jcbPesquisaProduto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProdutos = new javax.swing.JTable();
        jpnlProdutoCadastro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtCodigo = new javax.swing.JTextField();
        jtxtDescricao = new javax.swing.JTextField();
        jcbSituacao = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jtabCotacao = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblCotacao = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jcbPesquisaCotacao = new javax.swing.JComboBox<>();
        jtxtPesquisaCotacao = new javax.swing.JTextField();
        jbtnPesquisarCotacao = new javax.swing.JButton();
        jbtnExportarCotacao = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jcbCotacaoProdutos = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jtxtCotacaoValorProduto = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbCotacaoFornecedor = new javax.swing.JComboBox<>();
        jtxtCotacaoValidade = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtCotacaoCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtnNovo = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de tela 2021-03-25 212354.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cotações");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtabPrincipal.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jtabPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabPrincipalMouseClicked(evt);
            }
        });

        jtabProdutos.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel10.setForeground(new java.awt.Color(153, 153, 153));

        jbtnExportacao.setText("Exportar");

        jbtnPesquisarProduto.setText("Pesquisar");
        jbtnPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPesquisarProdutoActionPerformed(evt);
            }
        });

        jcbPesquisaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Descrição", "Situação", " " }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbPesquisaProduto, 0, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnPesquisarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnExportacao)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExportacao)
                    .addComponent(jbtnPesquisarProduto)
                    .addComponent(jcbPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jtblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jtblProdutos);

        javax.swing.GroupLayout jpnlProdutoListagemLayout = new javax.swing.GroupLayout(jpnlProdutoListagem);
        jpnlProdutoListagem.setLayout(jpnlProdutoListagemLayout);
        jpnlProdutoListagemLayout.setHorizontalGroup(
            jpnlProdutoListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlProdutoListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlProdutoListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnlProdutoListagemLayout.setVerticalGroup(
            jpnlProdutoListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlProdutoListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtabProdutos.addTab("Listagem", jpnlProdutoListagem);

        jLabel3.setText("Situação");

        jLabel2.setText("Descrição");

        jLabel1.setText("Código");

        jtxtCodigo.setEditable(false);

        jcbSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jpnlProdutoCadastroLayout = new javax.swing.GroupLayout(jpnlProdutoCadastro);
        jpnlProdutoCadastro.setLayout(jpnlProdutoCadastroLayout);
        jpnlProdutoCadastroLayout.setHorizontalGroup(
            jpnlProdutoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlProdutoCadastroLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jpnlProdutoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jpnlProdutoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtCodigo)
                    .addComponent(jtxtDescricao)
                    .addComponent(jcbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jpnlProdutoCadastroLayout.setVerticalGroup(
            jpnlProdutoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlProdutoCadastroLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jpnlProdutoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jpnlProdutoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jpnlProdutoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jtabProdutos.addTab("Cadastro", jpnlProdutoCadastro);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtabProdutos)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtabProdutos)
                .addContainerGap())
        );

        jtabPrincipal.addTab("Produtos", jPanel2);

        jtabCotacao.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jtabCotacao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtabCotacaoStateChanged(evt);
            }
        });

        jtblCotacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Valor", "Fornecedor", "Data", "Validade"
            }
        ));
        jtblCotacao.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jtblCotacao);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jcbPesquisaCotacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Descrição", "Situação", " " }));

        jbtnPesquisarCotacao.setText("Pesquisar");
        jbtnPesquisarCotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPesquisarCotacaoActionPerformed(evt);
            }
        });

        jbtnExportarCotacao.setText("Exportar");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbPesquisaCotacao, 0, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtPesquisaCotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnPesquisarCotacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnExportarCotacao)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPesquisaCotacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExportarCotacao)
                    .addComponent(jbtnPesquisarCotacao)
                    .addComponent(jcbPesquisaCotacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jtabCotacao.addTab("Listagem", jPanel11);

        jLabel7.setText("Produtos");

        jLabel8.setText("Valor");

        jtxtCotacaoValorProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jLabel5.setText("Fornecedor");

        jcbCotacaoFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtxtCotacaoValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabel4.setText("Validade");

        jtxtCotacaoCodigo.setEditable(false);

        jLabel6.setText("Código");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtCotacaoValidade, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                            .addComponent(jtxtCotacaoCodigo)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbCotacaoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbCotacaoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtCotacaoValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtCotacaoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtCotacaoValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbCotacaoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jcbCotacaoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCotacaoValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jtabCotacao.addTab("Cadastro", jPanel6);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtabCotacao)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtabCotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtabPrincipal.addTab("Cotações", jPanel5);

        jbtnNovo.setText("Novo");
        jbtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNovoActionPerformed(evt);
            }
        });

        jbtnEditar.setText("Editar");
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });

        jbtnSalvar.setText("Salvar");
        jbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarActionPerformed(evt);
            }
        });

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCancelar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNovo)
                    .addComponent(jbtnEditar)
                    .addComponent(jbtnSalvar)
                    .addComponent(jbtnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jtabPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtabPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNovoActionPerformed
        switch (jtabPrincipal.getSelectedIndex()) {
            case 0:
                novoProduto();
                break;
            case 1:
                novaCotacao();
                break;
        }
    }//GEN-LAST:event_jbtnNovoActionPerformed

    private void jbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarActionPerformed
        switch (jtabPrincipal.getSelectedIndex()) {
            case 0:
                cadastrarProduto();
                break;
            case 1:
                cadastrarCotacao();
                break;
        }
    }//GEN-LAST:event_jbtnSalvarActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        switch (jtabPrincipal.getSelectedIndex()) {
            case 0:
                editarProduto();
                break;
            case 1:
                editarCotacao();
                break;
        }
    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jbtnPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPesquisarProdutoActionPerformed
        try {
            List<Produto> produtos;
            
            if (!("").equals(jtxtPesquisaProduto.getText())) {
                switch (jcbPesquisaProduto.getSelectedIndex()) {
                    case 0:
                        produtos = produtoRepository.findById(Integer.parseInt(jtxtPesquisaProduto.getText().trim()));
                        break;
                    case 1:
                        produtos = produtoRepository.findByDescricaoIgnoreCaseContaining(jtxtPesquisaProduto.getText());
                        break;
                    case 2: produtos = produtoRepository.findBySituacaoIgnoreCaseContaining(jtxtPesquisaProduto.getText()); 
                        break;
                    default:
                        produtos = (List<Produto>)produtoRepository.findAll();
                }
            } else {
                produtos = (List<Produto>)produtoRepository.findAll();
            }

            preencherTableProdutos(produtos);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Código do produto inválido.", "ACME", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro inesperado. \nDetalhe: " + e.getMessage(), "ACME", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnPesquisarProdutoActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        modificarEstado(MODO_LISTAGEM);
        limparCadastroProduto();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jtabCotacaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtabCotacaoStateChanged
        
        
    }//GEN-LAST:event_jtabCotacaoStateChanged

    private void jtabPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabPrincipalMouseClicked
        Iterable<Produto> produtos = produtoRepository.findAll();
        
        jcbCotacaoProdutos.removeAllItems();
        
        for (Produto produto : produtos) {
            jcbCotacaoProdutos.addItem(produto);
        }
    }//GEN-LAST:event_jtabPrincipalMouseClicked

    private void jbtnPesquisarCotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPesquisarCotacaoActionPerformed
        List<Cotacao> cotacoes = (List<Cotacao>)cotacaoRepository.findAll();
        preencherTableCotacao(cotacoes);
    }//GEN-LAST:event_jbtnPesquisarCotacaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnExportacao;
    private javax.swing.JButton jbtnExportarCotacao;
    private javax.swing.JButton jbtnNovo;
    private javax.swing.JButton jbtnPesquisarCotacao;
    private javax.swing.JButton jbtnPesquisarProduto;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JComboBox<String> jcbCotacaoFornecedor;
    private javax.swing.JComboBox<Produto> jcbCotacaoProdutos;
    private javax.swing.JComboBox<String> jcbPesquisaCotacao;
    private javax.swing.JComboBox<String> jcbPesquisaProduto;
    private javax.swing.JComboBox<String> jcbSituacao;
    private javax.swing.JPanel jpnlProdutoCadastro;
    private javax.swing.JPanel jpnlProdutoListagem;
    private javax.swing.JTabbedPane jtabCotacao;
    private javax.swing.JTabbedPane jtabPrincipal;
    private javax.swing.JTabbedPane jtabProdutos;
    private javax.swing.JTable jtblCotacao;
    private javax.swing.JTable jtblProdutos;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtCotacaoCodigo;
    private javax.swing.JFormattedTextField jtxtCotacaoValidade;
    private javax.swing.JFormattedTextField jtxtCotacaoValorProduto;
    private javax.swing.JTextField jtxtDescricao;
    private javax.swing.JTextField jtxtPesquisaCotacao;
    private javax.swing.JTextField jtxtPesquisaProduto;
    // End of variables declaration//GEN-END:variables

    private void preencherTableProdutos(List<Produto> produtos) {
        DefaultTableModel model = (DefaultTableModel) jtblProdutos.getModel();
        model.setNumRows(0);

        jtblProdutos.getColumnModel().getColumn(0).setWidth(50);
        jtblProdutos.getColumnModel().getColumn(0).setHeaderValue("Código");
        jtblProdutos.getColumnModel().getColumn(1).setPreferredWidth(500); 
        jtblProdutos.getColumnModel().getColumn(1).setHeaderValue("Descrição");
        jtblProdutos.getColumnModel().getColumn(2).setPreferredWidth(100); 
        jtblProdutos.getColumnModel().getColumn(2).setHeaderValue("Situação");

        if (produtos != null) {
            for (Produto produto : produtos) {
                model.addRow(new Object[]{
                    produto.getId(),
                    produto.getDescricao(),
                    produto.getSituacao()
                });
            }
        }
    }
    
    private void preencherTableCotacao(List<Cotacao> cotacoes){
        DefaultTableModel model = (DefaultTableModel) jtblCotacao.getModel();
        model.setNumRows(0);

        jtblCotacao.getColumnModel().getColumn(0).setWidth(50);
        jtblCotacao.getColumnModel().getColumn(0).setHeaderValue("Código");
        jtblCotacao.getColumnModel().getColumn(1).setPreferredWidth(300); 
        jtblCotacao.getColumnModel().getColumn(1).setHeaderValue("Produto");
        jtblCotacao.getColumnModel().getColumn(2).setPreferredWidth(100); 
        jtblCotacao.getColumnModel().getColumn(2).setHeaderValue("Valor");
        jtblCotacao.getColumnModel().getColumn(3).setPreferredWidth(200); 
        jtblCotacao.getColumnModel().getColumn(3).setHeaderValue("Fornecedor");
        jtblCotacao.getColumnModel().getColumn(4).setPreferredWidth(100); 
        jtblCotacao.getColumnModel().getColumn(4).setHeaderValue("Data");
        jtblCotacao.getColumnModel().getColumn(5).setPreferredWidth(100); 
        jtblCotacao.getColumnModel().getColumn(5).setHeaderValue("Validade");

        if (cotacoes != null) {
            for (Cotacao cotacao : cotacoes) {
                model.addRow(new Object[]{
                    cotacao.getId(),
                    cotacao.getProduto().getDescricao(),
                    cotacaoValidation.formatarMoeda(cotacao.getValorProduto()),
                    cotacao.getFornecedor(),
                    cotacaoValidation.formatarData(cotacao.getData()),
                    cotacaoValidation.formatarData(cotacao.getValidade())
                });
            }
        }
    }

    private void cadastrarProduto() {
        try {
            Produto produto = new Produto();
            produto.setId("".equals(jtxtCodigo.getText()) ? 0 : Integer.parseInt(jtxtCodigo.getText()));
            produto.setDescricao(jtxtDescricao.getText());
            produto.setSituacao(jcbSituacao.getSelectedItem().toString());

            produtoValidation.validar(produto);

            int codigo = produtoRepository.save(produto).getId();

            JOptionPane.showMessageDialog(null, "Produto salvo com sucesso.", "ACME", JOptionPane.INFORMATION_MESSAGE);

            preencherTableProdutos((List<Produto>)produtoRepository.findById(codigo));

            modificarEstado(MODO_LISTAGEM);
            
            limparCadastroProduto();
            
        } catch (ProdutoInvalidoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ACME", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro inesperado. \nDetalhe: " + e.getMessage(), "ACME", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cadastrarCotacao() {
        try {
            Cotacao cotacao = new Cotacao();
            cotacao.setId("".equals(jtxtCotacaoCodigo.getText()) ? 0 : Integer.parseInt(jtxtCotacaoCodigo.getText())) ;
            cotacao.setData(new Date());
            cotacao.setValidade(formatDate(jtxtCotacaoValidade.getText()));
            cotacao.setProduto((Produto) jcbCotacaoProdutos.getSelectedItem());
            
            String valor = jtxtCotacaoValorProduto.getText().replace(".", "").replace(",", ".");
            
            cotacao.setValorProduto(Double.parseDouble(valor));
            cotacao.setFornecedor(jcbCotacaoFornecedor.getSelectedItem().toString());
            
            cotacaoValidation.validar(cotacao);
            
            cotacaoRepository.save(cotacao);
            
            JOptionPane.showMessageDialog(null, "Cotação cadastrada com sucesso.", "ACME", JOptionPane.WARNING_MESSAGE);
            
            modificarEstado(MODO_LISTAGEM);
            
        }catch(CotacaoInvalidaException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "ACME", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro inesperado. \nDetalhe: " + e.getMessage(), "ACME", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void novoProduto() {
        modificarEstado(MODO_CADASTRO);
    }

    private void novaCotacao() {
        modificarEstado(MODO_CADASTRO);
    }

    private void editarProduto() {
        int linha = jtblProdutos.getSelectedRow(); // retorna a linha selecionada pelo usuario

        if (linha >= 0) {
            jtxtCodigo.setText(jtblProdutos.getValueAt(linha, 0).toString()); // retorna o valor da celula linha X 0
            jtxtDescricao.setText(jtblProdutos.getValueAt(linha, 1).toString()); // retorna o valor da celula linha X 1
            jcbSituacao.setSelectedItem(jtblProdutos.getValueAt(linha, 2).toString()); // retorna o valor da celula linha X 2

            modificarEstado(MODO_CADASTRO);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o produto para poder editar.", "ACME", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void editarCotacao() {
        int linha = jtblCotacao.getSelectedRow(); // retorna a linha selecionada pelo usuario

        if (linha >= 0) {
           int codigo = Integer.parseInt(jtblCotacao.getValueAt(linha, 0).toString());
            Optional<Cotacao> cotacao = cotacaoRepository.findById(codigo);
            
            jtxtCotacaoCodigo.setText(cotacao.get().getId().toString());
            jtxtCotacaoValidade.setText(cotacaoValidation.formatarData(cotacao.get().getValidade()));
            jcbCotacaoProdutos.setSelectedItem(cotacao.get().getProduto());
            jcbCotacaoFornecedor.setSelectedItem(cotacao.get().getFornecedor());
            jtxtCotacaoValorProduto.setText(cotacaoValidation.formatarMoeda(cotacao.get().getValorProduto()));
            
            modificarEstado(MODO_CADASTRO);
        }
    }


    //ESTADOS DA TELA
    private void modificarEstado(boolean estado) {
        jbtnEditar.setEnabled(!estado);
        jbtnNovo.setEnabled(!estado);

        jbtnSalvar.setEnabled(estado);
        jbtnCancelar.setEnabled(estado);

        if (jtabPrincipal.getSelectedIndex() == TAB_PRODUTO) {
            if (estado == MODO_CADASTRO) {
                jtabProdutos.setSelectedIndex(1);
                jtxtDescricao.requestFocus();
            } else {
                jtabProdutos.setSelectedIndex(0);
            }
        } else {
            if (estado == MODO_CADASTRO) {
                jtabCotacao.setSelectedIndex(1);
                jtxtCotacaoValidade.requestFocus();
            } else {
                jtabCotacao.setSelectedIndex(0);
            }
        }
        
        
    }

    private void limparCadastroProduto() {
        jtxtCodigo.setText("");
        jtxtDescricao.setText("");
        jcbSituacao.setSelectedIndex(0);
    }
    
    
    private void carregarFornecedores()
    {
        String[] fornecedores = {"Fornecedor 01", "Fornecedor 02", "Fornecedor 03", "Fornecedor 04"};
        
        jcbCotacaoFornecedor.removeAllItems();
        
        for (int i = 0; i < fornecedores.length; i++) {
            jcbCotacaoFornecedor.addItem(fornecedores[i]);
        }
    }

    private Date formatDate(String data) throws ParseException
    {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");    
        Date date = sdf.parse(data);
        return date;
    }

   
}
